from cmu_graphics import *
from userMaze import *
from PIL import Image
from autoGeneratedMazeClasses import *
from autoGeneratedMaze import *

#penguin sprite credit https://spelunky.fyi/mods/m/penguin-skin-sprite-sheet/
#background credit : https://www.pinterest.com/pin/806144402050136524/
#credit for autoMazeGenExit portal art: https://www.pngwing.com/en/free-png-btexh
#credit for powerUp potion image: https://www.desertcart.ie/products/27470818-square-mana-potion-kit-decorative-glass-bottle-blue
#credit to this website for the free auto generated logo https://looka.com/?gclid=CjwKCAjw8symBhAqEiwAaTA__LaY0tAaMTQOtmWo1RuYUEohuXS6kx6Xa7tO59wyLAfVgwthVlkuKhoCgwEQAvD_BwE


#ui buttons relating to the mainscreen, use the button class from userMazeClasses.py
userButton = button(70,185,'Play the user generated maze',260,50,15,'red')
autoButton = button(70,275,'Play the auto generated maze',260,50,15,'blue')
resetButton = button(350,5,'Back',50,30,10,'yellow')

#initializes the UI buttons to change between the screens

def onAppStart(app):
    app.width = app.height = 400
    app.stepsPerSecond = 10
    app.screen = 'main'
   



def redrawAll(app):
    back = CMUImage(Image.open('back1.jpg'))
    drawImage(back,0,0,width = app.width, height = app.height)
    logoImage = CMUImage(Image.open('logo.png'))
    
    if not app.screen == 'main':
        resetButton.draw()
    if app.screen == 'main':
        scale = 1.5
        drawImage(logoImage,(400 - 200*scale)/2,75,width = 200*scale,height = 50*scale)
        autoButton.draw()
        userButton.draw()
    if app.screen == 'userMaze':
        userMazeScreenDraw(app)
    elif app.screen == 'autoGeneratedMaze':
        autoMazeDraw(app)
            

    
def onStep(app):
    if app.screen == 'userMaze':
        userMazeOnStep(app)
    elif app.screen == 'autoGeneratedMaze':
        autoMazeOnStep(app)

def onMousePress(app,mouseX,mouseY):
    if resetButton.isClicked(mouseX,mouseY):
        app.screen = 'main'
    elif app.screen == 'main':
        if autoButton.isClicked(mouseX,mouseY):
            app.screen = 'autoGeneratedMaze'
        if userButton.isClicked(mouseX,mouseY):
            app.screen = 'userMaze'

    elif app.screen == 'userMaze':
        userMazeOnMousePress(app,mouseX,mouseY)
    elif app.screen == 'autoGeneratedMaze':
        autoMazeMousePress(app,mouseX,mouseY)
        
        
        


def onKeyPress(app,key):
    if app.screen == 'userMaze':
        userMazeOnKeyPress(app,key)

    elif app.screen == 'autoGeneratedMaze':
        autoMazeOnKeyPress(app,key)

runApp()